DROP DATABASE IF EXISTS ToDanPho7;
CREATE DATABASE ToDanPho7;
USE ToDanPho7;


-- 1. BẢNG NHÂN KHẨU
CREATE TABLE NHAN_KHAU (
    MANHANKHAU INT AUTO_INCREMENT PRIMARY KEY,
    SOHOKHAU INT,  -- Sẽ liên kết với HO_KHAU sau
    HOTEN NVARCHAR(50) NOT NULL,
    BIDANH NVARCHAR(50) DEFAULT NULL,
    NGAYSINH DATE NOT NULL,
    GIOITINH NVARCHAR(3) NOT NULL,
    NOISINH NVARCHAR(100) NOT NULL,
    NGUYENQUAN NVARCHAR(100) NOT NULL,
    DANTOC NVARCHAR(30) NOT NULL,
    QUOCTICH NVARCHAR(20) NOT NULL,
    NGHENGHIEP NVARCHAR(50),
    CCCD NVARCHAR(15) UNIQUE NOT NULL,
    NGAYCAP DATE,
    NOICAP NVARCHAR(100),
    QUANHECHUHO NVARCHAR(20),
    TRANGTHAI NVARCHAR(50) NOT NULL,
    NOITHUONGTRUCU NVARCHAR(100)
) ENGINE=InnoDB;


-- 2. BẢNG HỘ KHẨU
CREATE TABLE HO_KHAU (
    SOHOKHAU INT AUTO_INCREMENT PRIMARY KEY,
    MACHUHO INT NOT NULL,  -- Liên kết đến nhân khẩu là chủ hộ
    DIACHI NVARCHAR(100) NOT NULL,
    HOSOSO INT NOT NULL,
    SODANGKYSO INT NOT NULL,
    TOSO INT NOT NULL,
    DELETE_FLAG BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (MACHUHO) REFERENCES NHAN_KHAU(MANHANKHAU)
) ENGINE=InnoDB;




-- 3. BẢNG TẠM TRÚ
CREATE TABLE TAM_TRU (
    MATAMTRU INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT NOT NULL,
    NGAYBATDAU DATE NOT NULL,
    NGAYKETTHUC DATE NOT NULL,
    DIACHITAMTRU NVARCHAR(200) NOT NULL,
    GHICHU NVARCHAR(255),
    FOREIGN KEY (MANHANKHAU) REFERENCES NHAN_KHAU(MANHANKHAU)
) ENGINE=InnoDB;


-- 4. BẢNG TẠM VẮNG
CREATE TABLE TAM_VANG (
    MATAMVANG INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT NOT NULL,
    NGAYBATDAU DATE NOT NULL,
    NGAYKETTHUC DATE NOT NULL,
    LYDO NVARCHAR(100),
    GHICHU NVARCHAR(100),
    FOREIGN KEY (MANHANKHAU) REFERENCES NHAN_KHAU(MANHANKHAU)
) ENGINE=InnoDB;


-- 5. BẢNG THAY ĐỔI NHÂN KHẨU
CREATE TABLE THAY_DOI_NHAN_KHAU (
    MATDNK INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT NOT NULL,
    LOAITHAYDOI NVARCHAR(50) NOT NULL,
    NOICHUYEN NVARCHAR(100),
    NGAYTHAYDOI DATE NOT NULL,
    FOREIGN KEY (MANHANKHAU) REFERENCES NHAN_KHAU(MANHANKHAU)
) ENGINE=InnoDB;


-- 6. BẢNG THAY ĐỔI HỘ KHẨU
CREATE TABLE THAY_DOI_HO_KHAU (
    MATDKH INT AUTO_INCREMENT PRIMARY KEY,
    SOHOKHAU INT NOT NULL,
    NOIDUNG NVARCHAR(500),
    NGAYTHAYDOI DATE NOT NULL,
    FOREIGN KEY (SOHOKHAU) REFERENCES HO_KHAU(SOHOKHAU)
) ENGINE=InnoDB;


-- 7. BẢNG TÀI SẢN
CREATE TABLE TAI_SAN (
    MATAISAN INT AUTO_INCREMENT PRIMARY KEY,
    TENTAISAN NVARCHAR(50) NOT NULL,
    SOLUONG INT NOT NULL,
    TINHTRANG NVARCHAR(50) NOT NULL
) ENGINE=InnoDB;


-- 8. BẢNG HOẠT ĐỘNG
CREATE TABLE HOAT_DONG (
    MASUKIEN INT AUTO_INCREMENT PRIMARY KEY,
    TENSUKIEN NVARCHAR(100) NOT NULL,
    NGAYTOCHUC DATE NOT NULL,
    LOAISUKIEN NVARCHAR(100) NOT NULL,
    PHISUDUNG DECIMAL(12,2) NOT NULL,
    TRANGTHAIDUYET NVARCHAR(50) NOT NULL
) ENGINE=InnoDB;


-- 9. BẢNG TÀI KHOẢN
CREATE TABLE TAI_KHOAN (
    MATAIKHOAN INT AUTO_INCREMENT PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    CHUCVU NVARCHAR(30) NOT NULL,
    TENDANGNHAP VARCHAR(50) UNIQUE NOT NULL,
    MATKHAU VARCHAR(255) NOT NULL,
    TRANGTHAI BOOLEAN DEFAULT TRUE  -- TRUE: hoạt động, FALSE: khóa
) ENGINE=InnoDB;


