
DROP DATABASE IF EXISTS ToDanPho7; -- Xóa cơ sở dữ liệu nếu đã tồn tại
CREATE DATABASE ToDanPho7; -- Tạo cơ sở dữ liệu mới
USE ToDanPho7; -- Sử dụng cơ sở dữ liệu vừa tạo

-- 1. Bảng HO_KHAU
CREATE TABLE HO_KHAU (
    SOHOKHAU INT AUTO_INCREMENT PRIMARY KEY,
    HOTENCHUHO NVARCHAR(50) NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    HOSOSO INT NOT NULL,
    SODANGKYSO INT NOT NULL,
    TOSO INT NOT NULL
) ENGINE=InnoDB;

-- 2. Bảng NHAN_KHAU
CREATE TABLE NHAN_KHAU (
    MANHANKHAU INT AUTO_INCREMENT PRIMARY KEY,
    SOHOKHAU INT NOT NULL,
    HOTEN NVARCHAR(50) NOT NULL,
    BIDANH NVARCHAR(50) DEFAULT NULL,
    NGAYSINH DATE NOT NULL,
    GIOITINH NVARCHAR(3) NOT NULL,
    NOISINH NVARCHAR(100) NOT NULL,
    NGUYENQUAN NVARCHAR(100) NOT NULL,
    DANTOC NVARCHAR(30) NOT NULL,
    QUOCTICH NVARCHAR(20) NOT NULL,
    NGHENGHIEP NVARCHAR(20),
    SOCCCD VARCHAR(12) UNIQUE NOT NULL,
    NGAYCAP DATE,
    NOICAP NVARCHAR(100) NOT NULL,
    QUANHECHUHO NVARCHAR(20) NOT NULL,
    TRANGTHAI NVARCHAR(50) NOT NULL,
    NOITHUONGTRUCU NVARCHAR(100),
    FOREIGN KEY (SOHOKHAU) REFERENCES HO_KHAU(SOHOKHAU)
) ENGINE=InnoDB;

-- 3. Bảng TAM_TRU
CREATE TABLE TAM_TRU (
    MATAMTRU INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT NOT NULL,
    NGAYBATDAU DATE NOT NULL,
    NGAYKETTHUC DATE NOT NULL,
    DIACHITAMTRU NVARCHAR(200) NOT NULL,
    GHICHU NVARCHAR(255),
    FOREIGN KEY (MANHANKHAU) REFERENCES NHAN_KHAU(MANHANKHAU)
) ENGINE=InnoDB;

-- 4. Bảng TAM_VANG
CREATE TABLE TAM_VANG (
    MATAMVANG INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT NOT NULL,
    NGAYBATDAU DATE NOT NULL,
    NGAYKETTHUC DATE NOT NULL,
    LYDO NVARCHAR(100),
    GHICHU NVARCHAR(100),
    FOREIGN KEY (MANHANKHAU) REFERENCES NHAN_KHAU(MANHANKHAU)
) ENGINE=InnoDB;

-- 5. Bảng THAY_DOI_NHAN_KHAU
CREATE TABLE THAY_DOI_NHAN_KHAU (
    MATDNK INT AUTO_INCREMENT PRIMARY KEY,
    MANHANKHAU INT NOT NULL,
    LOAITHAYDOI NVARCHAR(10) NOT NULL,
    NOICHUYEN NVARCHAR(100) ,
    NGAYTHAYDOI DATE NOT NULL,
    FOREIGN KEY (MANHANKHAU) REFERENCES NHAN_KHAU(MANHANKHAU)
) ENGINE=InnoDB;

-- 6. Bảng THAY_DOI_HO_KHAU
CREATE TABLE THAY_DOI_HO_KHAU (
    MATDKH INT AUTO_INCREMENT PRIMARY KEY,
    SOHOKHAU INT NOT NULL,
    NOIDUNG NVARCHAR(100),
    NGAYTHAYDOI DATE NOT NULL,
    FOREIGN KEY (SOHOKHAU) REFERENCES HO_KHAU(SOHOKHAU)
) ENGINE=InnoDB;


-- 7. Bảng TAI_SAN
CREATE TABLE TAI_SAN (
    MATAISAN INT AUTO_INCREMENT PRIMARY KEY,
    TENTAISAN NVARCHAR(50) NOT NULL,
    SOLUONG INT NOT NULL,
    TINHTRANG NVARCHAR(50) NOT NULL
) ENGINE=InnoDB;

-- 8. Bảng HOAT_DONG
CREATE TABLE HOAT_DONG (
    MASUKIEN INT AUTO_INCREMENT PRIMARY KEY,
    TENSUKIEN NVARCHAR(100) NOT NULL,
    NGAYTOCHUC DATE NOT NULL,
    LOAISUKIEN NVARCHAR(100) NOT NULL,
    PHISUDUNG DECIMAL(12,2) NOT NULL,
    TRANGTHAIDUYET NVARCHAR(50) NOT NULL
) ENGINE=InnoDB;

-- 9. Bảng TAI_KHOAN
CREATE TABLE TAI_KHOAN (
    MATAIKHOAN INT AUTO_INCREMENT PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    CHUCVU NVARCHAR(30) NOT NULL,
    TENDANGNHAP VARCHAR(50) UNIQUE NOT NULL,
    MATKHAU VARCHAR(255) NOT NULL
) ENGINE=InnoDB;






